# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test-controller
      - run: npm start &
      - run: sleep 5
      - run: npm run test-external
      - uses: grafana/setup-k6-action@v1
        name: Setup K6

      - uses: grafana/run-k6-action@v1
        id: run_k6
        name: Run k6 test
        env:
          BASE_URL: ${{ secrets.BASE_URL}}
          K6_WEB_DASHBOARD: true
          K6_WEB_DASHBOARD_EXPORT: html-report.html
        with:
          path: ./tests/k6/*.test.js
          cloud-run-locally: true
          cloud-comment-on-pr: true

      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          # Directory containing the static site files
          path: './report/'